version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  heroku_deploy:
    jobs:
      # - build
      - deploy:
          # requires:
          #   - build
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          DATABASE_URL: postgres://postgres:password@localhost:5432/frontlearn-ams_test
          RAILS_ENV: test
      - image: circleci/postgres:11.5-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      # Yarn for dependenscies e.g webpack
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      # Database setup
      - run: bundle exec rake db:create db:schema:load

      - run: bundle exec rspec

      # Save test results
      - store_test_results:
          path: /tmp/test-results

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
      - run:
          command: |
            heroku run rake db:migrate -app frontlearn-ams
            sleep 5 -app frontlearn-ams
            heroku restart -app frontlearn-ams
